"""SFZ exporter — the lingua franca format.

Kontakt, TAL Sampler, Sforzando, and most modern samplers import SFZ,
so this doubles as the Kontakt path (File > Import in Kontakt 7+).
"""
from __future__ import annotations

from pathlib import Path

from exporters.mapping import InstrumentMap


def export_sfz(imap: InstrumentMap, output_path: Path, samples_relative_to: Path | None = None) -> Path:
    base = samples_relative_to or output_path.parent
    lines = [
        f"// {imap.name}",
        "// Generated by VST Sampling Factory",
        "",
        "<control>",
        "default_path=",
        "",
        "<global>",
        "ampeg_release=0.4",
        "",
    ]

    rr_count = imap.round_robin_count
    for zone in imap.zones:
        try:
            sample_ref = zone.sample_path.relative_to(base)
        except ValueError:
            sample_ref = zone.sample_path
        lines.append("<region>")
        lines.append(f"sample={sample_ref.as_posix()}")
        lines.append(f"pitch_keycenter={zone.root_note}")
        lines.append(f"lokey={zone.low_note} hikey={zone.high_note}")
        lines.append(f"lovel={zone.low_vel} hivel={zone.high_vel}")
        if imap.one_shot:
            lines.append("loop_mode=one_shot")
        if rr_count > 1:
            lines.append(f"seq_length={rr_count} seq_position={zone.round_robin + 1}")
        if zone.has_loop:
            lines.append("loop_mode=loop_continuous")
            lines.append(f"loop_start={zone.loop_start} loop_end={zone.loop_end}")
        lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path
